name: Sync Feishu Group Members

on:
  workflow_dispatch:
    inputs:
      bitable_url:
        description: '飞书多维表格URL'
        required: true
        type: string
      chat_id:
        description: '飞书群ID'
        required: true
        type: string
  schedule:
    # 每天北京时间上午9点执行 (UTC+8 = UTC+8, 所以是UTC 1点)
    - cron: '0 1 * * *'

env:
  FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
  FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}

jobs:
  sync-members:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create config file
      run: |
        cat > config.py << 'EOF'
        #!/usr/bin/env python3
        # -*- coding: utf-8 -*-
        """
        飞书API配置文件
        请根据实际情况修改以下配置
        """

        # 飞书应用配置
        FEISHU_CONFIG = {
            # 应用ID
            "app_id": "cli_a757be749210500e",
            
            # 应用密钥
            "app_secret": "EvAyrNVzqxV7Wp3gET8oA5tjAt1T5ZfJ"
        }

        # API配置
        API_CONFIG = {
            # 飞书开放平台API基础URL
            "base_url": "https://open.feishu.cn/open-apis",
            
            # 请求间隔时间（秒）
            "request_interval": 0.1,
            
            # 批量处理大小
            "batch_size": 500,
            
            # token提前刷新时间（秒）
            "token_refresh_advance": 300
        }

        # 日志配置
        LOG_CONFIG = {
            # 日志级别
            "level": "INFO",
            
            # 日志文件名
            "filename": "feishu_sync.log",
            
            # 日志格式
            "format": "%(asctime)s - %(levelname)s - %(message)s"
        }
        EOF
        
    - name: Run sync script (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "${{ github.event.inputs.chat_id }}" | python feishu_group_members.py "${{ github.event.inputs.bitable_url }}"
        
    - name: Run sync script (scheduled)
      if: github.event_name == 'schedule'
      run: |
        # 这里需要配置默认的表格URL和群ID，或者从secrets中读取
        echo "${{ secrets.DEFAULT_CHAT_ID }}" | python feishu_group_members.py "${{ secrets.DEFAULT_BITABLE_URL }}"
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs
        path: feishu_sync.log
        retention-days: 30